name: Branch-Driven EKS Lifecycle with Manual Review

on:
  push:
    branches:
      - 'feature/**'    # Triggers dev plan/apply
      - develop        # Triggers qa plan/gated apply
      - main           # Triggers prod plan/gated apply
# pull_request:
#   types: [closed]
#   branches:
#     - 'feature/**'    # Triggers dev destroy upon PR merge

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.s3-vars.outputs.env_name }}
      tf_action: ${{ steps.s3-vars.outputs.tf_action }}
      should_run: ${{ steps.s3-vars.outputs.should_run }}
    steps:
      - name: Grab today's date and save it
        id: s3-vars
        run: |
          # Format the date (e.g., 20261007)
          CURRENT_DATE=$(date +'%Y%m%d')
          TODAYS_NAME="${{ vars.BUCKET_NAME }}-$CURRENT_DATE"
          echo "CURRENT_DATE [$CURRENT_DATE]"
          echo "AWS_REGION [${{ vars.AWS_REGION }}]"
          echo "BUCKET_NAME [${{ vars.BUCKET_NAME }}]"
          echo "TODAYS_NAME [$TODAYS_NAME]"
          echo "TODAYS_BUCKET_NAME=$TODAYS_NAME" >> "$GITHUB_OUTPUT"
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> "$GITHUB_OUTPUT"

  s3-list-buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Show existing buckets
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          args: s3 ls

  create-bucket:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.s3-vars.outputs.env_name }}
      tf_action: ${{ steps.s3-vars.outputs.tf_action }}
      should_run: ${{ steps.s3-vars.outputs.should_run }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Grab today's date and save it
        id: s3-vars
        run: |
          chmod +x ./scripts/createS3Bucket.sh
          ./scripts/createS3Bucket.sh